# Generated by Django 5.2.15 on 2026-09-21 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('departments', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Complaint Status',
                'verbose_name_plural': 'Complaint Statuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CivicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('ward_name', models.CharField(default='Ward Central', max_length=150)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=350000.0, max_digits=12)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('priority_score', models.FloatField(default=0.0)),
                ('priority_percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed Cluster'), ('VOTED_FOR_FUNDING', 'Voted for Funding'), ('IN_EXECUTION', 'In Execution'), ('COMPLETED', 'Completed & Verified')], default='PROPOSED', max_length=30)),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='projects/resolutions/')),
                ('resolution_remarks', models.TextField(blank=True, null=True)),
                ('rejected_image', models.ImageField(blank=True, null=True, upload_to='projects/rejected_proofs/')),
                ('rejected_remarks', models.TextField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.complaintcategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.district')),
                ('rejected_by', models.ManyToManyField(blank=True, related_name='rejected_civic_projects', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_civic_projects', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.state')),
                ('verified_by', models.ManyToManyField(blank=True, related_name='verified_civic_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_ai_processed', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=15000.0, max_digits=12)),
                ('budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='complaints/resolutions/')),
                ('resolution_remarks', models.TextField(blank=True)),
                ('is_ngo_assisted', models.BooleanField(default=False, help_text='Filed by registered NGO on behalf of rural citizen')),
                ('ngo_name', models.CharField(blank=True, help_text='Name of assisting NGO', max_length=150)),
                ('rural_citizen_name', models.CharField(blank=True, help_text='Name of rural citizen beneficiary', max_length=150)),
                ('rural_citizen_phone', models.CharField(blank=True, help_text='Mobile phone number of rural citizen beneficiary', max_length=15)),
                ('rejection_reason', models.TextField(blank=True, help_text='Citizen rejection feedback when officer resolution is disputed')),
                ('rejection_image', models.ImageField(blank=True, help_text='Citizen photo proof showing issue remains unresolved', null=True, upload_to='complaints/rejections/')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified_resolved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='categories.complaintcategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='departments.department')),
                ('department_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='departments.departmentoffice')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='locations.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='locations.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.complaintstatus')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CivicProjectResolutionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='projects/resolutions/')),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_proofs', to='complaints.civicproject')),
                ('rejected_by', models.ManyToManyField(blank=True, related_name='rejected_proof_photos', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ManyToManyField(blank=True, related_name='verified_proof_photos', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_proofs', to='complaints.complaint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='civicproject',
            name='complaints',
            field=models.ManyToManyField(blank=True, related_name='civic_projects', to='complaints.complaint'),
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='complaints/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Image',
                'verbose_name_plural': 'Complaint Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complaints.complaint')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_status_history', to='complaints.complaintstatus')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_status_history', to='complaints.complaintstatus')),
            ],
            options={
                'verbose_name': 'Complaint Status History',
                'verbose_name_plural': 'Complaint Status Histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CivicProjectVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='complaints.civicproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_vote')],
            },
        ),
        migrations.CreateModel(
            name='ComplaintSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Support',
                'verbose_name_plural': 'Complaint Supports',
                'constraints': [models.UniqueConstraint(fields=('complaint', 'user'), name='unique_complaint_support')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fiscal_year', models.CharField(default='2025-2026', max_length=20)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=2500000.0, max_digits=14)),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='departments.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_budgets', to='locations.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_budgets', to='locations.state')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department', 'district', 'fiscal_year'), name='unique_dept_district_budget')],
            },
        ),
    ]
